# Generated by Django 5.1.7 on 2025-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeModelCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='generateurcv/cv_images/')),
                ('preview_image', models.ImageField(upload_to='cv_images/previews/')),
                ('premium', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(default='CV', max_length=50)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
