# Generated by Django 5.1.7 on 2025-05-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0002_listemodelcv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listemodelcv',
            name='preview_image',
        ),
    ]
