# Generated by Django 5.1.7 on 2025-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0003_remove_listemodelcv_preview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listemodelcv',
            old_name='name',
            new_name='auteur',
        ),
        migrations.RemoveField(
            model_name='listemodelcv',
            name='author',
        ),
        migrations.AddField(
            model_name='listemodelcv',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listemodelcv',
            name='image',
            field=models.ImageField(upload_to='cv_images/'),
        ),
    ]
