# Generated by Django 5.1.7 on 2025-05-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0004_rename_name_listemodelcv_auteur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeModelCV',
        ),
    ]
