# Generated by Django 5.1.7 on 2025-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0005_delete_listemodelcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitelogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_texte', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
