# Generated by Django 5.1.7 on 2025-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0007_resumetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplate',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
