# Generated by Django 5.1.7 on 2025-05-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0008_remove_resumetemplate_preview_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
    ]
