# Generated by Django 5.1.7 on 2025-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0010_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
