# Generated by Django 5.1.7 on 2025-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0011_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AproposHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte_1', models.TextField()),
                ('texte_2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte_1', models.TextField()),
                ('texte_2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
