# Generated by Django 5.1.7 on 2025-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0012_aproposheader_histoire_mission_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='equipe_titre',
            field=models.CharField(default='Notre Équipe', max_length=200),
        ),
        migrations.AddField(
            model_name='valeur',
            name='valeurs_titre',
            field=models.CharField(default='Nos Valeurs', max_length=200),
        ),
    ]
