# Generated by Django 5.1.7 on 2025-05-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0013_teammember_equipe_titre_valeur_valeurs_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe_titre', models.CharField(default='Notre Équipe', max_length=200)),
                ('valeurs_titre', models.CharField(default='Nos Valeurs', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='equipe_titre',
        ),
        migrations.RemoveField(
            model_name='valeur',
            name='valeurs_titre',
        ),
    ]
