# Generated by Django 5.1.7 on 2025-05-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0014_sectiontitre_remove_teammember_equipe_titre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aproposheader',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='histoire',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='sectiontitre',
            name='equipe_titre',
        ),
        migrations.RemoveField(
            model_name='sectiontitre',
            name='valeurs_titre',
        ),
        migrations.AddField(
            model_name='sectiontitre',
            name='titre_equipe',
            field=models.CharField(default='Notre Équipe', max_length=255),
        ),
        migrations.AddField(
            model_name='sectiontitre',
            name='titre_header',
            field=models.CharField(default='À propos de CV Craft Magic', max_length=255),
        ),
        migrations.AddField(
            model_name='sectiontitre',
            name='titre_histoire',
            field=models.CharField(default='Notre Histoire', max_length=255),
        ),
        migrations.AddField(
            model_name='sectiontitre',
            name='titre_mission',
            field=models.CharField(default='Notre Mission', max_length=255),
        ),
        migrations.AddField(
            model_name='sectiontitre',
            name='titre_valeurs',
            field=models.CharField(default='Nos Valeurs', max_length=255),
        ),
    ]
