# Generated by Django 5.1.7 on 2025-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0015_remove_aproposheader_titre_remove_histoire_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
