# Generated by Django 5.1.7 on 2025-06-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0016_cv_html_url_cv_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
