# Generated by Django 5.1.7 on 2025-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0018_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='image_url',
        ),
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
