# Generated by Django 5.1.7 on 2025-06-11 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0019_remove_herosection_image_url_herosection_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='image',
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generateurcv.herosection')),
            ],
        ),
    ]
