# Generated by Django 5.1.7 on 2025-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0022_temoignage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
