# Generated by Django 5.1.7 on 2025-06-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0023_cv_address_cv_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
