# Generated by Django 5.1.7 on 2025-06-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0024_alter_cv_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='website',
        ),
    ]
