# Generated by Django 5.1.7 on 2025-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateurcv', '0025_remove_cv_address_remove_cv_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
